[project]
name = "machinelearningpipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "dagshub>=0.6.3",
  "dvc>=3.64.1",
  "dvc-s3>=3.2.2",
  "mlflow==2.22.0",
  "scikit-learn>=1.7.2",
]
